# -*- coding: utf-8 -*-
"""ML Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPJcfwpq4LVG6nX0WxCnuE5khet-kOM2
"""

!pip install git+https://github.com/pycaret/pycaret.git@master --upgrade

import pycaret
pycaret.__version__

from google.colab import drive
drive.mount('/content/drive')
csv_file = "/content/drive/MyDrive/parkinsons_updrs.data"

import pycaret
from pycaret.datasets import get_data


data = get_data('parkinsons')

from pycaret.regression import setup

s = setup(
    data=data,
    target='total_UPDRS',
    ignore_features=['motor_UPDRS','subject#','age']
)

from pycaret.regression import compare_models, create_model

# compare baseline models
best = compare_models()

from pycaret.regression import compare_models, create_model
best = create_model('et')

from pycaret.regression import plot_model
plot_model(best, plot = 'residuals')

plot_model(best, plot = 'error')

plot_model(best, plot = 'feature')

from pycaret.regression import predict_model
holdout_pred = predict_model(best)

holdout_pred.head()

new_data = data.copy()
new_data.drop('total_UPDRS', axis=1, inplace=True)
new_data.head()

predictions = predict_model(best, data = new_data)
predictions.head()

from pycaret.regression import save_model
save_model(best, 'my_first_pipeline')

from pycaret.regression import load_model
loaded_best_pipeline = load_model('my_first_pipeline')
loaded_best_pipeline